build:
  image: bjodah/bjodahimg16dev:v1.3
  environment:
    - PYCVODES_LAPACK=lapack,blas
  commands:
    - ./scripts/ci.sh pycvodes
    - cd tests/; make; cd -
    - cd tests/; make EXTRA_FLAGS=-DNDEBUG; cd -
    - cd tests/; make CXX=clang++-5.0 EXTRA_FLAGS=-fsanitize=address -B; cd -
    - cd tests/; make CXX=clang++-5.0 EXTRA_FLAGS=-fsanitize=undefined -B; cd -
    - (cd examples/; jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - python3 -m pip install --user -e .[docs]
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
    - bash -c '[[ $(python setup.py --version 2>/dev/null) =~ ^[0-9]+.* ]]'

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pycvodes
    source: deploy/
    target: ~
    recursive: true
    delete: false
