{% set name = "pycvodes" %}
{% set version = "0.6.0.git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.18*  # [not win]
    - sundials
    - python
    - cython
    - numpy
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.18*  # [not win]
    - sundials
    - python
    - numpy

test:
  imports:
    - pycvodes
# requires:
#     - pytest
# commands:
#     - py.test --pyargs pycvodes  # https://github.com/conda/conda/issues/2075, https://github.com/pytest-dev/pytest/issues/1445

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around cvodes (from the sundials library)'
  doc_url: https://bjodah.github.io/{{ name }}


extra:
  recipe-maintainers:
    - bjodah
