{% set name = "pycvodes" %}
{% set version = "0.8.0+git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19*  # [not win]
    - sundials
    - python
    - cython
    - numpy
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19*  # [not win]
    - sundials
    - python
    - numpy

test:
  imports:
    - pycvodes

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around cvodes (from the sundials library)'
  doc_url: https://bjodah.github.io/{{ name }}/latest


extra:
  recipe-maintainers:
    - bjodah
